import React, { useState } from 'react';
import { Map, CheckSquare, Calendar, BookOpen, Youtube, ExternalLink, Award } from 'lucide-react';

export default function RoadmapView() {
  const [missions, setMissions] = useState([
    { id: 1, title: "Learn Docker & Containerization", xp: 150, deadline: "Aug 10", status: "completed" },
    { id: 2, title: "Deploy FastAPI Backend on Railway", xp: 200, deadline: "Aug 17", status: "in_progress" },
    { id: 3, title: "Solve 5 LeetCode Medium DSA Problems", xp: 100, deadline: "Aug 24", status: "pending" },
    { id: 4, title: "Implement Redis Caching Layer", xp: 180, deadline: "Aug 31", status: "pending" },
  ]);

  const toggleMission = (id) => {
    setMissions(missions.map(m => {
      if (m.id === id) {
        return { ...m, status: m.status === 'completed' ? 'pending' : 'completed' };
      }
      return m;
    }));
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
      <div>
        <h2>Personalized Career Roadmap & Weekly Missions</h2>
        <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem' }}>Structured 12-week roadmap generated by Groq AI based on your current skills and target role.</p>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1.5fr 1fr', gap: '24px' }}>
        {/* Left Column: Weekly Missions Checklist */}
        <div className="glass-panel" style={{ padding: '24px', display: 'flex', flexDirection: 'column', gap: '16px' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <h3>Active Weekly AI Missions</h3>
            <span style={{ fontSize: '0.8rem', background: 'rgba(99, 102, 241, 0.1)', color: '#6366f1', padding: '4px 10px', borderRadius: '12px' }}>
              630 XP Earned
            </span>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
            {missions.map(mission => (
              <div
                key={mission.id}
                onClick={() => toggleMission(mission.id)}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: '14px',
                  padding: '14px',
                  borderRadius: 'var(--radius-md)',
                  background: mission.status === 'completed' ? 'rgba(16, 185, 129, 0.05)' : 'rgba(255, 255, 255, 0.02)',
                  border: '1px solid',
                  borderColor: mission.status === 'completed' ? 'rgba(16, 185, 129, 0.3)' : 'var(--border-color)',
                  cursor: 'pointer',
                  transition: 'var(--transition)'
                }}
              >
                <input
                  type="checkbox"
                  checked={mission.status === 'completed'}
                  onChange={() => {}}
                  style={{ width: '18px', height: '18px', accentColor: '#6366f1' }}
                />
                <div style={{ flex: 1 }}>
                  <h4 style={{ fontSize: '0.95rem', textDecoration: mission.status === 'completed' ? 'line-through' : 'none', color: mission.status === 'completed' ? 'var(--text-muted)' : 'var(--text-primary)' }}>
                    {mission.title}
                  </h4>
                  <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Deadline: {mission.deadline}</p>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '4px', background: 'rgba(245, 158, 11, 0.1)', color: '#f59e0b', padding: '4px 8px', borderRadius: '8px', fontSize: '0.75rem', fontWeight: 600 }}>
                  <Award size={14} />
                  +{mission.xp} XP
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Right Column: Curated Learning Resources */}
        <div className="glass-panel" style={{ padding: '24px', display: 'flex', flexDirection: 'column', gap: '16px' }}>
          <h3>Curated Recommended Resources</h3>
          
          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
            <a href="https://kubernetes.io/docs/tutorials/" target="_blank" rel="noreferrer" style={{ textDecoration: 'none', color: 'inherit' }}>
              <div style={{ padding: '12px', borderRadius: '8px', background: 'rgba(255,255,255,0.03)', border: '1px solid var(--border-color)', display: 'flex', alignItems: 'center', gap: '12px' }}>
                <BookOpen size={20} color="#06b6d4" />
                <div style={{ flex: 1 }}>
                  <h4 style={{ fontSize: '0.85rem' }}>Kubernetes Official Tutorial</h4>
                  <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Documentation • 3 hours</p>
                </div>
                <ExternalLink size={14} color="var(--text-muted)" />
              </div>
            </a>

            <a href="https://youtube.com" target="_blank" rel="noreferrer" style={{ textDecoration: 'none', color: 'inherit' }}>
              <div style={{ padding: '12px', borderRadius: '8px', background: 'rgba(255,255,255,0.03)', border: '1px solid var(--border-color)', display: 'flex', alignItems: 'center', gap: '12px' }}>
                <Youtube size={20} color="#ec4899" />
                <div style={{ flex: 1 }}>
                  <h4 style={{ fontSize: '0.85rem' }}>Redis Crash Course for Python</h4>
                  <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>YouTube • 45 minutes</p>
                </div>
                <ExternalLink size={14} color="var(--text-muted)" />
              </div>
            </a>
          </div>
        </div>
      </div>
    </div>
  );
}
